import { chromium } from "@playwright/test";
import { pathToFileURL } from "url";
const OUT = "C:/Users/adrie/AppData/Local/Temp/claude/C--Users-adrie-AI-Projects-jobcrush-app/60400e99-3888-486e-9a22-849bb0a26b3f/scratchpad";
const FILE = "C:/Users/adrie/AI/Projects/jobcrush-app/apps/web/prototypes/profile-desktop-options.prototype.html";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.on("pageerror", e => console.log("PAGE ERROR:", e.message));
await page.goto(pathToFileURL(FILE).href);
await page.waitForTimeout(900);
await page.locator('.switcher button[data-v="C"]').click();
await page.waitForTimeout(1800);
await page.screenshot({ path: `${OUT}/C-sky-fixed.png` });
await page.locator('.switcher button[data-v="B"]').click();
await page.waitForTimeout(600);
await page.locator(".vB").evaluate(el => el.scrollTo(0, el.scrollHeight));
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/B-bottom-fixed.png` });
await browser.close();
console.log("done");
