#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — issue #32: shared-infra spend alerts + Fly token scope.
# Everything an agent could do from the CLI is already done. What is left needs
# a human in a browser, or a human judgement about money.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

FLY_BIN="${FLY_BIN:-$HOME/.fly/bin/fly}"

# open_url override for Git Bash on Windows. The library tries explorer.exe,
# which returns a non-zero exit code even when it succeeds — so the wizard
# reports "couldn't open a browser" every time — and MSYS rewrites the '/' in a
# URL path into a Windows path before explorer sees it. PowerShell has neither
# problem. Measured on this machine 2026-08-13; the library itself is untouched.
if command -v powershell.exe >/dev/null 2>&1; then
  open_url() {
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$1"
    MSYS2_ARG_CONV_EXCL='*' powershell.exe -NoProfile -Command "Start-Process '$1'" \
      >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $1"
  }
fi

banner "Shared infra — spend alerts and Fly token scope (#32)"

# ── Stage 1 — Cloudflare budget alert ─────────────────────────────────────
stage "Cloudflare — budget alert"
say "Both projects share ONE Cloudflare account and ONE card."
say "A budget alert emails you when account-wide usage-based spend crosses a"
say "figure you pick. It only warns — it never caps or pauses anything."
say ""
say "Pay-as-you-go accounts only. If you are on the free plan the button will"
say "not be there; that is expected, and there is nothing to do here."
open_url "https://dash.cloudflare.com/?to=/:account/billing/billable-usage"
step "Manage Account -> Billing -> Billable Usage."
step "Click 'Create budget alert'."
step "Set a monthly figure you would want to hear about, and your email."
ask CF_BUDGET "What figure did you set? (e.g. 20 USD, or 'none — free plan'):"
pause "Budget alert saved (or confirmed not available)?"

# ── Stage 2 — Fly has no alerts; look at the meter instead ────────────────
stage "Fly — month-to-date bill (no alert exists)"
say "Fly does NOT support billing alerts or a spending cap. Their own docs say:"
say "  \"We don't support billing alerts (yet), so budget accordingly.\""
say ""
say "So there is nothing to switch on. The only cost control Fly offers is"
say "looking. Both projects' machines auto-stop, so a runaway machine is the"
say "risk this stage exists to catch early."
open_url "https://fly.io/dashboard/personal/billing"
step "Read the 'current month to date' figure."
ask FLY_MTD "What does it say? (e.g. 4.20 USD):"
say ""
say "If that number is not roughly what you expect, check for machines that"
say "should have stopped:  $FLY_BIN machines list -a <app>"
pause "Noted?"

# ── Stage 3 — no org-wide Fly tokens should remain ────────────────────────
stage "Fly — confirm no org-wide deploy tokens remain"
say "An org-wide token can deploy or destroy EVERY app on the shared account."
say "Both projects should use one app-scoped token per app instead."
say ""
if [[ ! -x "$FLY_BIN" ]] && ! command -v fly >/dev/null 2>&1; then
  say "flyctl not found at $FLY_BIN — skipping this check."
  SKIPPED+=("Fly org-token check (flyctl not found)")
else
  command -v fly >/dev/null 2>&1 && FLY_BIN="$(command -v fly)"
  ORG_TOKEN_IDS=$("$FLY_BIN" tokens list -s org -o personal 2>/dev/null     | awk -F'│' '$2 ~ /Org deploy token/ && $5 ~ /^ *$/ {gsub(/ /,"",$1); if ($1 != "") print $1}')
  if [[ -z "$ORG_TOKEN_IDS" ]]; then
    say "None found. Every deploy token on the account is app-scoped."
  else
    say "Org-wide tokens still present:"
    printf '    %s
' $ORG_TOKEN_IDS
    say ""
    say "Revoking these breaks any CI still using one. vitacairn and jobcrush"
    say "both use app-scoped tokens now, so nothing here should need them."
    if confirm "Revoke them?"; then
      # shellcheck disable=SC2086
      "$FLY_BIN" tokens revoke $ORG_TOKEN_IDS && say "Revoked."
    else
      SKIPPED+=("Fly org-wide tokens left alive (declined)")
    fi
  fi
fi
pause "Done here?"

say ""
say "Recorded this run:  Cloudflare budget = ${CF_BUDGET:-?}   Fly MTD = ${FLY_MTD:-?}"
say "Update the checkboxes in SHARED_INFRA.md and on issue #32."
# ──────────────────────────────────────────────────────────────────────────

finish
